apiVersion: v1
kind: Secret
metadata:
  name: minio-admin
  namespace: {{ .Release.Namespace }}

type: Opaque
data:
  # generate 32 chars long random string, base64 encode it and then double-quote the result string.
  minio-admin-user: {{ randAlphaNum 32 | b64enc | quote }}
  minio-admin-password: {{ randAlphaNum 32 | b64enc | quote }}

---

# Create deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-singleuser
  namespace: {{ .Release.Namepace }}  
  labels:
    app: minio-singleuser
spec:
  replicas: 1
  minReadySeconds: 20
  selector:
    matchLabels:
      app: minio-singleuser
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: minio-singleuser
        tier: service
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}

    spec:
      containers:
      - name: minio
        image: "minio/minio"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
        - containerPort: 9000
        - containerPort: 9001
        env:
        - name: MINIO_ROOT_USER
          valueFrom: 
            secretKeyRef:
              name: minio-admin 
              key: minio-admin-user
        - name: MINIO_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: minio-admin 
              key: minio-admin-password

        command:
          - minio
          - server
          - "/data"
          - "--console-address"
          - ":9001"

        volumeMounts:
          - name: data
            mountPath: /data
            readOnly: False

      volumes:
        - name: data
          hostPath:
            path: {{ .Values.vkdMinioServerHostPath }}
            type: DirectoryOrCreate 

      tolerations:
        {{ .Values.vkdMinioServerTolerations | toYaml | nindent 8 }}

      nodeSelector:
        {{ .Values.vkdMinioServerNodeSelector | toYaml | nindent 8 }}

---

apiVersion: v1
kind: Service
metadata:
  name: minio-singleuser
  namespace: {{ .Release.Namepace }}  
  labels:
    app: minio-singleuser
    tier: service
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 9000
      protocol: TCP
    - name: console
      port: 9001
      protocol: TCP
  selector:
    app: minio-singleuser






