# Image name: harbor.cloud.infn.it/testbed-dm/ai-infn:v4.0.5
FROM docker.io/jgvino/jupyterhub-jlab:v2

# Install apptainer, cvmfs and openssh-server
RUN apt update && \
    apt-get install -y gnupg2 && \
    apt install -y lsb-release wget software-properties-common && \
    wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb && \
    dpkg -i cvmfs-release-latest_all.deb && \
    add-apt-repository -y ppa:apptainer/ppa && \
    apt update  && \
    apt install -y \
      apptainer \
      cvmfs \
      cvmfs-fuse3 \
      cvmfs-libs \
      openssh-server \
      libgl1-mesa-glx \
      xvfb \
    && \
    apt-get clean && rm -rf /var/lib/apt/lists/* cvmfs-release-latest_all.deb 

# Install customized JuiceFS client
RUN wget -O /usr/bin/juicefs https://pandora.infn.it/public/3423df/dl/juicefs && \
    chmod a+rx /usr/bin/juicefs

# Changes the home directory of the user to private
RUN sed -i 's/:\/root:/:\/home\/private:/g' /etc/passwd

# Import configuration of sshd
COPY ./sshd.conf /etc/ssh/sshd_config.d/aiinfn.conf 

# Clean home of default jupyter user
RUN rm -rf /home/jovyan

WORKDIR /home
ENTRYPOINT []

