apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-issuer
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: l.anderlini@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: lets-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  name: jhubaas
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: proxy-public
            port:
              name: http
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: jhub-tls



