## Adds a ClusterRole and a ClusterRoleBinding to enable listing nodes
## to retrieve information on the available resources.

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.jhubServiceAccount }}
  namespace: {{ .Values.jhubNamespace }}
rules:
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["nodes"]
    verbs: ["get", "watch", "list"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.jhubServiceAccount }}
  namespace: {{ .Values.jhubNamespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.jhubServiceAccount }}
    namespace: {{ .Values.jhubNamespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.jhubServiceAccount }}
  apiGroup: rbac.authorization.k8s.io

